<?php

namespace Claroline\CoreBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class DesktopController__JMSInjector
{
    public static function inject($container) {
        require_once '/home/jenkins/jobs/Release/workspace/app/cache/dev/jms_diextra/proxies/Claroline-CoreBundle-Controller-DesktopController.php';
        $g = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Claroline\\CoreBundle\\Controller\\DesktopController' => array('widgetsWithoutConfigAction' => array(0 => 'security.access.method_interceptor'), 'widgetsWithConfigAction' => array(0 => 'security.access.method_interceptor'), 'renderToolListAction' => array(0 => 'security.access.method_interceptor'), 'openToolAction' => array(0 => 'security.access.method_interceptor'), 'openAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxybafd91b3_6eb2fa14bce3f2a13bba152832de15b89404cd22\__CG__\Claroline\CoreBundle\Controller\DesktopController($container->get('doctrine.orm.entity_manager', 1), $container->get('claroline.event.event_dispatcher', 1), $container->get('claroline.manager.home_tab_manager', 1), $container->get('router', 1), $container->get('claroline.manager.tool_manager', 1));
        $instance->__CGInterception__setLoader($g);
        return $instance;
    }
}
