<?php

namespace Claroline\CoreBundle\Controller\Badge;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ProfileController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Claroline\CoreBundle\Controller\Badge\ProfileController();
        return $instance;
    }
}
