<?php

namespace Claroline\CoreBundle\Controller\Tool;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class HomeController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Claroline\CoreBundle\Controller\Tool\HomeController($container->get('doctrine.orm.entity_manager', 1), $container->get('claroline.event.event_dispatcher', 1), $container->get('claroline.form.factory', 1), $container->get('claroline.manager.home_tab_manager', 1), $container->get('request', 1), $container->get('claroline.manager.role_manager', 1), $container->get('security.context', 1), $container->get('claroline.manager.tool_manager', 1), $container->get('claroline.manager.widget_manager', 1));
        return $instance;
    }
}
