<?php

namespace Claroline\VideoPlayerBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class VideoPlayerController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Claroline\VideoPlayerBundle\Controller\VideoPlayerController();
        return $instance;
    }
}
