<?php

namespace Claroline\CoreBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class MailController__JMSInjector
{
    public static function inject($container) {
        require_once '/home/jenkins/jobs/Release/workspace/app/cache/dev/jms_diextra/proxies/Claroline-CoreBundle-Controller-MailController.php';
        $d = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Claroline\\CoreBundle\\Controller\\MailController' => array('formAction' => array(0 => 'security.access.method_interceptor'), 'sendAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxybafd91b3_91f3c5a5a59abd994aeb1796233a91ed5941e275\__CG__\Claroline\CoreBundle\Controller\MailController($container->get('claroline.form.factory', 1), $container->get('request', 1), $container->get('claroline.manager.mail_manager', 1), $container->get('router', 1), $container->get('security.context', 1), $container->get('claroline.config.platform_config_handler', 1));
        $instance->__CGInterception__setLoader($d);
        return $instance;
    }
}
