<?php

namespace Claroline\CoreBundle\Controller\Tool;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class RolesController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Claroline\CoreBundle\Controller\Tool\RolesController($container->get('claroline.manager.role_manager', 1), $container->get('claroline.manager.user_manager', 1), $container->get('claroline.manager.group_manager', 1), $container->get('claroline.manager.resource_manager', 1), $container->get('security.context', 1), $container->get('claroline.form.factory', 1), $container->get('router', 1), $container->get('request', 1));
        return $instance;
    }
}
