<?php

namespace Claroline\CoreBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ActivityController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Claroline\CoreBundle\Controller\ActivityController($container->get('claroline.manager.resource_manager', 1), $container->get('request', 1), $container->get('translator', 1));
        return $instance;
    }
}
