<?php

namespace Claroline\CoreBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class MessageController__JMSInjector
{
    public static function inject($container) {
        require_once '/home/jenkins/jobs/Release/workspace/app/cache/dev/jms_diextra/proxies/Claroline-CoreBundle-Controller-MessageController.php';
        $b = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Claroline\\CoreBundle\\Controller\\MessageController' => array('formForGroupAction' => array(0 => 'security.access.method_interceptor'), 'sendAction' => array(0 => 'security.access.method_interceptor'), 'listReceivedAction' => array(0 => 'security.access.method_interceptor'), 'listSentAction' => array(0 => 'security.access.method_interceptor'), 'listRemovedAction' => array(0 => 'security.access.method_interceptor'), 'showAction' => array(0 => 'security.access.method_interceptor'), 'softDeleteAction' => array(0 => 'security.access.method_interceptor'), 'deleteAction' => array(0 => 'security.access.method_interceptor'), 'restoreFromTrashAction' => array(0 => 'security.access.method_interceptor'), 'markAsReadAction' => array(0 => 'security.access.method_interceptor'), 'contactableUsersListAction' => array(0 => 'security.access.method_interceptor'), 'contactableGroupsListAction' => array(0 => 'security.access.method_interceptor'), 'checkAccess' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxybafd91b3_48b8d92badd5c5e63f554c20e9458a06fa9a128e\__CG__\Claroline\CoreBundle\Controller\MessageController($container->get('request', 1), $container->get('router', 1), $container->get('claroline.form.factory', 1), $container->get('claroline.manager.message_manager', 1), $container->get('claroline.manager.group_manager', 1), $container->get('claroline.manager.user_manager', 1), $container->get('claroline.manager.workspace_manager', 1), $container->get('security.context', 1), $container->get('claroline.security.utilities', 1), $container->get('claroline.pager.pager_factory', 1));
        $instance->__CGInterception__setLoader($b);
        return $instance;
    }
}
