<?php

namespace Claroline\CoreBundle\Controller\Badge;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AdminController__JMSInjector
{
    public static function inject($container) {
        require_once '/home/jenkins/jobs/Release/workspace/app/cache/dev/jms_diextra/proxies/Claroline-CoreBundle-Controller-Badge-AdminController.php';
        $f = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Claroline\\CoreBundle\\Controller\\Badge\\AdminController' => array('listAction' => array(0 => 'security.access.method_interceptor'), 'addAction' => array(0 => 'security.access.method_interceptor'), 'editAction' => array(0 => 'security.access.method_interceptor'), 'deleteAction' => array(0 => 'security.access.method_interceptor'), 'awardAction' => array(0 => 'security.access.method_interceptor'), 'unawardAction' => array(0 => 'security.access.method_interceptor'), 'manageClaimAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxybafd91b3_be49f7544aa71ff804e9e9ca06c7fd61e5767ad0\__CG__\Claroline\CoreBundle\Controller\Badge\AdminController();
        $instance->__CGInterception__setLoader($f);
        return $instance;
    }
}
