<?php

namespace Claroline\CoreBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AdministrationHomeTabController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Claroline\CoreBundle\Controller\AdministrationHomeTabController($container->get('claroline.form.factory', 1), $container->get('claroline.manager.home_tab_manager', 1), $container->get('request', 1), $container->get('claroline.manager.widget_manager', 1));
        return $instance;
    }
}
