<?php

namespace Claroline\CoreBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ResourceController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Claroline\CoreBundle\Controller\ResourceController($container->get('security.context', 1), $container->get('claroline.manager.resource_manager', 1), $container->get('claroline.manager.rights_manager', 1), $container->get('claroline.manager.role_manager', 1), $container->get('translator', 1), $container->get('request', 1), $container->get('claroline.event.event_dispatcher', 1), $container->get('claroline.manager.mask_manager', 1));
        return $instance;
    }
}
