<?php

namespace Claroline\CoreBundle\Controller\Tool;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class WorkspaceParametersController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Claroline\CoreBundle\Controller\Tool\WorkspaceParametersController($container->get('claroline.manager.workspace_manager', 1), $container->get('claroline.manager.workspace_tag_manager', 1), $container->get('security.context', 1), $container->get('claroline.event.event_dispatcher', 1), $container->get('claroline.form.factory', 1), $container->get('router', 1), $container->get('request', 1));
        return $instance;
    }
}
