<?php

namespace Claroline\CoreBundle\Controller\Tool;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AdministrationToolController__JMSInjector
{
    public static function inject($container) {
        require_once '/home/jenkins/jobs/Release/workspace/app/cache/dev/jms_diextra/proxies/Claroline-CoreBundle-Controller-Tool-AdministrationToolController.php';
        $i = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Claroline\\CoreBundle\\Controller\\Tool\\AdministrationToolController' => array('showToolAction' => array(0 => 'security.access.method_interceptor'), 'modifyToolAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxybafd91b3_714394198e816565b20be1a7bba0d79d46b3c2e1\__CG__\Claroline\CoreBundle\Controller\Tool\AdministrationToolController($container->get('request', 1), $container->get('claroline.manager.tool_manager', 1), $container->get('claroline.form.factory', 1), $container->get('router', 1));
        $instance->__CGInterception__setLoader($i);
        return $instance;
    }
}
