<?php

namespace Claroline\CoreBundle\Controller\Badge\Tool;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class WorkspaceController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Claroline\CoreBundle\Controller\Badge\Tool\WorkspaceController();
        return $instance;
    }
}
