<?php

namespace Claroline\CoreBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class WorkspaceController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Claroline\CoreBundle\Controller\WorkspaceController($container->get('claroline.manager.home_tab_manager', 1), $container->get('claroline.manager.workspace_manager', 1), $container->get('claroline.manager.resource_manager', 1), $container->get('claroline.manager.role_manager', 1), $container->get('claroline.manager.user_manager', 1), $container->get('claroline.manager.workspace_tag_manager', 1), $container->get('claroline.manager.tool_manager', 1), $container->get('claroline.event.event_dispatcher', 1), $container->get('security.context', 1), $container->get('router', 1), $container->get('claroline.security.utilities', 1), $container->get('claroline.form.factory', 1), $container->get('claroline.security.token_updater', 1), $container->get('claroline.manager.widget_manager', 1));
        return $instance;
    }
}
