<?php

namespace Claroline\CoreBundle\Controller\Tool;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class WorkspaceToolsParametersController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Claroline\CoreBundle\Controller\Tool\WorkspaceToolsParametersController($container->get('claroline.manager.tool_manager', 1), $container->get('claroline.manager.role_manager', 1), $container->get('claroline.form.factory', 1), $container->get('request', 1));
        return $instance;
    }
}
