<?php

namespace Claroline\AnnouncementBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AnnouncementController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Claroline\AnnouncementBundle\Controller\AnnouncementController($container->get('claroline.announcement.manager.announcement_manager', 1), $container->get('form.factory', 1), $container->get('claroline.pager.pager_factory', 1), $container->get('security.context', 1), $container->get('translator', 1), $container->get('claroline.security.utilities', 1), $container->get('claroline.manager.workspace_manager', 1));
        return $instance;
    }
}
