<?php

namespace Claroline\CoreBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AuthenticationController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Claroline\CoreBundle\Controller\AuthenticationController($container->get('request', 1), $container->get('claroline.manager.user_manager', 1), $container->get('security.encoder_factory', 1), $container->get('claroline.persistence.object_manager', 1), $container->get('translator', 1), $container->get('claroline.form.factory', 1), $container->get('claroline.authenticator', 1), $container->get('claroline.manager.mail_manager', 1), $container->get('router', 1));
        return $instance;
    }
}
