<?php

namespace Icap\WikiBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ContributionController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Icap\WikiBundle\Controller\ContributionController($container->get('icap.wiki.contribution_manager', 1));
        return $instance;
    }
}
