<?php

namespace JMS\SecurityExtraBundle\Tests\Functional\TestBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PostController__JMSInjector
{
    public static function inject($container) {
        require_once '/home/jenkins/jobs/Release/workspace/app/cache/dev/jms_diextra/proxies/EnhancedProxy_73b88e6bf5989f9e4785cea753cad509a15376f1-__CG__-JMS-SecurityExtraBundle-Tests-Functional-TestBundle-Controller-PostController.php';
        $j = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('JMS\\SecurityExtraBundle\\Tests\\Functional\\TestBundle\\Controller\\PostController' => array('newPostAction' => array(0 => 'security.access.method_interceptor'), 'editPostAction' => array(0 => 'security.access.method_interceptor'), 'listPostAction' => array(0 => 'security.access.method_interceptor'), 'fooPostAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxybafd91b3_dfd68e3b7d24f73291d182582cfbe600406fb1ca\__CG__\JMS\SecurityExtraBundle\Tests\Functional\TestBundle\Controller\PostController();
        $instance->__jmsDiExtra_setContainer($container);
        $instance->__CGInterception__setLoader($j);
        $refProperty = new \ReflectionProperty('JMS\\SecurityExtraBundle\\Tests\\Functional\\TestBundle\\Controller\\PostController', 'request');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('request', 1));
        $refProperty = new \ReflectionProperty('JMS\\SecurityExtraBundle\\Tests\\Functional\\TestBundle\\Controller\\PostController', 'em');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('em', 1));
        $refProperty = new \ReflectionProperty('JMS\\SecurityExtraBundle\\Tests\\Functional\\TestBundle\\Controller\\PostController', 'context');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('security.context', 1));
        $refProperty = new \ReflectionProperty('JMS\\SecurityExtraBundle\\Tests\\Functional\\TestBundle\\Controller\\PostController', 'router');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('router', 1));
        return $instance;
    }
}
