<?php

namespace UJM\ExoBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class HintController__JMSInjector
{
    public static function inject($container) {
        $instance = new \UJM\ExoBundle\Controller\HintController();
        return $instance;
    }
}
